name: GameShell CI
on: [push]
jobs:
  test:
    strategy:
      matrix:
        platform: [macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout the GameShell repo
        uses: actions/checkout@v2
      - name: Run the tests
        run: |
            make tests-bash && make tests-zsh
